//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demkaTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderContents = new HashSet<OrderContents>();
        }
    
        public int id { get; set; }
        public string article { get; set; }
        public string name { get; set; }
        public int unitID { get; set; }
        public decimal cost { get; set; }
        public int supplierID { get; set; }
        public int manufacturerID { get; set; }
        public int categoryID { get; set; }
        public int discountPercent { get; set; }
        public int remains { get; set; }
        public string description { get; set; }
        public string photo { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderContents> OrderContents { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Units Units { get; set; }
    }
}
